#!/bin/sh

xrdb -merge $XDG_CONFIG_HOME/sx/Xresources

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
     for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
          [ -x "$f" ] && . "$f"
     done
     unset f
fi

# Autostart stuff that needs desktop
# e.g. nm-applet
systemctl --user start desktop.target &

#
# X things
#

# Set default cursor to left pointer instead of X
xsetroot -cursor_name left_ptr

# set key repeat rate
xset r rate 275 40

#
# background stuff
#

# Hides mouse when it hasn't been used for a while
unclutter &

#
# Window Manager and Compositor
#

picom -b
exec bspwm
