#!/bin/fish

# Get updates from Arch official repositories
if ! set arch_updates (checkupdates 2> /dev/null | wc -l)
    set arch_updates 0
end

# Get updates from Arch user repositories
# uses yay
if ! set aur_updates (yay -Qum 2> /dev/null | wc -l)
    set aur_updates 0
end

jo  arch=$arch_updates \
    aur=$aur_updates \
    total=(math $arch_updates + $aur_updates)
