#!/bin/sh

xrdb -merge $XDG_CONFIG_HOME/sx/Xresources

# Start dbus
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# Import Display so dunst can start correctly
systemctl --user import-environment DISPLAY

#
# X things
#

# Set default cursor to left pointer instead of X
xsetroot -cursor_name left_ptr

# set key repeat rate
xset r rate 275 40

#
# background stuff
#

# Hides mouse when it hasn't been used for a while
unclutter &

# Start udiskie to automount USB storage devices
udiskie &

# Torrent
qbittorrent-nox -d

# Start flexget daemon
flexget daemon start -d

#
# idk style stuff i guess
#

# Set last used background
nitrogen --restore

# Start compositor
picom -b

#
# window manager
#
exec bspwm
