#!/bin/sh

riverctl spawn 'kile'
sleep 0.5 &&

# layouts
BSP="(
        { vertical:
           full,
           (vertical: full)
        } 1 0.65 0
    )
"

ROW="((h : h d) 2 0.65 0)"

EXAMPLE="((v 1 0.5 0): h (h : v v))"
# Spawn kile and set it as default layout for all outputs
riverctl default-layout kile
#
# Kile options
#

# set default layout
riverctl send-layout-cmd kile "default $EXAMPLE"

# 4 is a nice number for gaps
# 2 + 2 = 4
riverctl send-layout-cmd kile "global_view_padding 2"
riverctl send-layout-cmd kile "global_outer_padding 2"


# kile bindings

# TODO
# Mod+H and Mod+L to decrease/increase the main_factor value of rivertile by 0.05
#riverctl map normal $mod M send-layout-cmd kile "main_ratio +0.05"
#riverctl map normal $mod I send-layout-cmd kile "main_ratio -0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main_count value of rivertile.
#riverctl map normal $mod+Shift M send-layout-cmd kile "main_amount +1"
#riverctl map normal $mod+Shift I send-layout-cmd kile "main_ration -1"
