#! /bin/sh

# Launch hotkey daemon
sxhkd -m 1 &

# Launch bar
$XDG_CONFIG_HOME/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width    2
bspc config window_gap      4

bspc config normal_border_color  '#333B47'
bspc config focused_border_color '#64B9F2'

bspc config split_ratio     0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Element desktop='^4'
bspc rule -a FreeTube desktop='^4'
bspc rule -a "Hydrus Client" desktop='^10'
