#! /bin/sh

# Launch hotkey daemon
sxhkd -m 1 &

# screen layout
xrandr --output DisplayPort-1  --primary  --output HDMI-A-1  --right-of DisplayPort-1 --dpi 96

# Launch bar
$XDG_CONFIG_HOME/polybar/launch.sh
bspc monitor DisplayPort-1 -d 1 2 3 4 5
bspc monitor HDMI-A-1 -d 6 7 8 9 0

bspc wm -O DisplayPort-1 HDMI-A-1

bspc config border_width    2
bspc config window_gap      4

bspc config normal_border_color  '#333B47'
bspc config focused_border_color '#64B9F2'

bspc config split_ratio     0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Element desktop='^4'
bspc rule -a FreeTube desktop='^4'
bspc rule -a "Hydrus Client" desktop='^10'

bspc rule -a steam_app_1468260 desktop='^7'


# wall

nitrogen --restore
