variables: secrets.yml
templates:
    
##### Anime series config
  anime-series:
    #include: anime.yml
    configure_series:
      from:
        entry_list: anilist-series
      settings:
        identified_by: sequence
        timeframe: 4 hours
        target: 1080p
        quality: 720p-1080p
        special_ids:
          - OVA
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'
      
##### Disable builtins for some tasks
  disable-seen-retry:
    disable:
      - seen
      - seen_info_hash
      - retry_failed
          
##### torrent config
  torrents:
    torrent_alive:
      min_seeds: 3
      reject_for: 15 minutes
    magnets: no
    domain_delay:
      nyaa: 3 seconds
      subsplease: 3 seconds
      
##### transmission anime
  transmission-anime:
    transmission:
      main_file_only: yes
      path: "/{? folder.media.root ?}{? folder.media.anime ?}{{title}}/"
      
##### transmission anime
  transmission-anime-series:
    transmission:
      main_file_only: yes
      content_filename: "{{series_name}} - ep{{series_id}} - [{{quality}}]"
      path: "/{? folder.media.root ?}{? folder.media.anime ?}{{series_name | pathscrub}}/"
      
##### Notify
  notify:
    notify:
      entries:
        title: "[flexget] {{task}}"
        message: "{{title}}"
        via:
          - toast: yes

tasks:
##### Fetch, format and output anilist series list to a custom entry list
  fill-anime-series:
    priority: 1
    template:
      - disable-seen-retry
    list_clear:
      what:
        - entry_list: anilist-series
    anilist:
      username: "{? anilist.username ?}"
      # Finished shows and movies I will find myself for now
      format:
        - tv
        - tv_short
      release_status: releasing
    set:
      # Use english title instead of romaji title
      # Torrents use SX instead of Season X
      # Anilist has seperate entries for series that airs in multiple parts or cours
      # Finally trim any spaces on the end
      title: "{{al_title.english |
                re_replace('Season ', 'S') |
                re_replace(' II$', ' S2') |
                re_replace(' III$', ' S3') |
                re_replace('(Cour|Part) [0-9]+', '') |
                re_replace(' $', '') }}"
    accept_all: yes
    list_add:
      - entry_list: anilist-series
       
##### Download anime from subsplease RSS feed
  download-anime-series-rss:
    priority: 15
    template:
      - anime-series
      - torrents
      - transmission-anime-series
      - notify
    inputs:
      - rss: https://subsplease.org/rss/?t&r=1080

##### Download anime from manually downloaded torrents
#
  download-anime-manual:
    priority: 14
    template:
      - disable-seen-retry
      - transmission-anime
      - notify
    filesystem:
      path: "/{? folder.torrent.root ?}{? folder.torrent.anime ?}"
      mask: '*.torrent'
    accept_all: yes
    exec:
      on_output:
        for_accepted: rm -f "{{location}}"
